# **Repaso pre-procesamiento datos**

Por: Mathias Lettere

Fecha última edición: 18/08/2023

## Pasos del Repaso

1.- DataFrame con los datos de los cuatro ficheros

### Librerías a usar

In [ ]:
import pandas as pd
import numpy as np
import datetime as dt

In [ ]:
#Montar csv del drive al libro
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

### Unificación del Dataframe

In [ ]:
#Crear Df
df1 = pd.read_csv('/content/drive/My Drive/emisiones-2016.csv', delimiter= ';')
df2 = pd.read_csv('/content/drive/My Drive/emisiones-2017.csv', delimiter= ';')
df3 = pd.read_csv('/content/drive/My Drive/emisiones-2018.csv', delimiter= ';')
df4 = pd.read_csv('/content/drive/My Drive/emisiones-2019.csv', delimiter= ';')

listDf =[df1, df2, df3, df4]

In [ ]:
dfEmisiones = pd.concat(listDf)
dfEmisiones.head

<bound method NDFrame.head of       PROVINCIA  MUNICIPIO  ESTACION  MAGNITUD PUNTO_MUESTREO   ANO  MES  \
0            28         79         4         1  28079004_1_38  2016    1
1            28         79         4         1  28079004_1_38  2016    2
2            28         79         4         1  28079004_1_38  2016    3
3            28         79         4         1  28079004_1_38  2016    4
4            28         79         4         1  28079004_1_38  2016    5
...         ...        ...       ...       ...            ...   ...  ...
1831         28         79        60        14  28079060_14_6  2019    8
1832         28         79        60        14  28079060_14_6  2019    9
1833         28         79        60        14  28079060_14_6  2019   10
1834         28         79        60        14  28079060_14_6  2019   11
1835         28         79        60        14  28079060_14_6  2019   12

       D01 V01    D02  ...   D27  V27   D28  V28   D29  V29    D30  V30   D31  \
0      8.0   V    7.0  ...   9.0    V   7.0    V   8.0    V    9.0    V   9.0
1     12.0   V   13.0  ...   7.0    V   8.0    V   9.0    V    0.0    N   0.0
2     11.0   V   10.0  ...   8.0    V   7.0    V   8.0    V   10.0    V   8.0
3      8.0   V    9.0  ...   9.0    V   8.0    V   8.0    V    8.0    V   0.0
4      7.0   V    8.0  ...   7.0    V   7.0    V   7.0    V    7.0    V   7.0
...    ...  ..    ...  ...   ...  ...   ...  ...   ...  ...    ...  ...   ...
1831  94.0   V  104.0  ...  88.0    V  90.0    V  99.0    V  108.0    V  98.0
1832  88.0   V   82.0  ...  54.0    V  68.0    V  70.0    V   55.0    V   0.0
1833  44.0   V   75.0  ...  28.0    V  33.0    V  16.0    V   19.0    V  47.0
1834  41.0   V   55.0  ...  55.0    V  52.0    V  47.0    V   56.0    V   0.0
1835  47.0   V   53.0  ...  17.0    V  13.0    V  14.0    V    5.0    V   4.0

      V31
0       V
1       N
2       V
3       N
4       V
...   ...
1831    V
1832    N
1833    V
1834    N
1835    V

[7266 rows x 69 columns]>

In [ ]:
dfEmisiones

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,D27,V27,D28,V28,D29,V29,D30,V30,D31,V31
0,28,79,4,1,28079004_1_38,2016,1,8.0,V,7.0,...,9.0,V,7.0,V,8.0,V,9.0,V,9.0,V
1,28,79,4,1,28079004_1_38,2016,2,12.0,V,13.0,...,7.0,V,8.0,V,9.0,V,0.0,N,0.0,N
2,28,79,4,1,28079004_1_38,2016,3,11.0,V,10.0,...,8.0,V,7.0,V,8.0,V,10.0,V,8.0,V
3,28,79,4,1,28079004_1_38,2016,4,8.0,V,9.0,...,9.0,V,8.0,V,8.0,V,8.0,V,0.0,N
4,28,79,4,1,28079004_1_38,2016,5,7.0,V,8.0,...,7.0,V,7.0,V,7.0,V,7.0,V,7.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1831,28,79,60,14,28079060_14_6,2019,8,94.0,V,104.0,...,88.0,V,90.0,V,99.0,V,108.0,V,98.0,V
1832,28,79,60,14,28079060_14_6,2019,9,88.0,V,82.0,...,54.0,V,68.0,V,70.0,V,55.0,V,0.0,N
1833,28,79,60,14,28079060_14_6,2019,10,44.0,V,75.0,...,28.0,V,33.0,V,16.0,V,19.0,V,47.0,V
1834,28,79,60,14,28079060_14_6,2019,11,41.0,V,55.0,...,55.0,V,52.0,V,47.0,V,56.0,V,0.0,N
1835,28,79,60,14,28079060_14_6,2019,12,47.0,V,53.0,...,17.0,V,13.0,V,14.0,V,5.0,V,4.0,V

2.- Filtrar las columnas del DataFrame (ESTACION, MAGNITUD, AÑO, MES y las correspondientes a los días D01, D02, etc)

3.- Reestructurar el DataFrame para que los valores de los contaminantes de las columnas de los días aparezcan en una única columna.

In [ ]:
#Filtración
cols = ['ESTACION', 'MAGNITUD', 'ANO', 'MES']
cols.extend([col for col in dfEmisiones if col.startswith('D')])

dfEmReduced = dfEmisiones[cols]
dfEmReduced

,ESTACION,MAGNITUD,ANO,MES,D01,D02,D03,D04,D05,D06,...,D22,D23,D24,D25,D26,D27,D28,D29,D30,D31
0,4,1,2016,1,8.0,7.0,6.0,6.0,7.0,6.0,...,10.0,11.0,11.0,13.0,12.0,9.0,7.0,8.0,9.0,9.0
1,4,1,2016,2,12.0,13.0,9.0,9.0,11.0,9.0,...,11.0,10.0,9.0,8.0,7.0,7.0,8.0,9.0,0.0,0.0
2,4,1,2016,3,11.0,10.0,9.0,9.0,7.0,8.0,...,8.0,8.0,9.0,9.0,9.0,8.0,7.0,8.0,10.0,8.0
3,4,1,2016,4,8.0,9.0,9.0,8.0,8.0,9.0,...,8.0,8.0,8.0,8.0,9.0,9.0,8.0,8.0,8.0,0.0
4,4,1,2016,5,7.0,8.0,9.0,9.0,8.0,8.0,...,7.0,7.0,8.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1831,60,14,2019,8,94.0,104.0,106.0,99.0,77.0,82.0,...,86.0,97.0,104.0,96.0,85.0,88.0,90.0,99.0,108.0,98.0
1832,60,14,2019,9,88.0,82.0,80.0,92.0,79.0,75.0,...,59.0,46.0,49.0,69.0,57.0,54.0,68.0,70.0,55.0,0.0
1833,60,14,2019,10,44.0,75.0,44.0,54.0,65.0,68.0,...,37.0,39.0,45.0,21.0,23.0,28.0,33.0,16.0,19.0,47.0
1834,60,14,2019,11,41.0,55.0,79.0,65.0,64.0,51.0,...,38.0,75.0,69.0,45.0,35.0,55.0,52.0,47.0,56.0,0.0
1835,60,14,2019,12,47.0,53.0,45.0,44.0,49.0,41.0,...,68.0,36.0,9.0,11.0,10.0,17.0,13.0,14.0,5.0,4.0

In [ ]:
dfEmReduced = dfEmReduced.melt(id_vars=['ESTACION', 'MAGNITUD', 'ANO', 'MES'], var_name='DIA', value_name='VALOR')
dfEmReduced

        ESTACION  MAGNITUD   ANO  MES  DIA  VALOR
0              4         1  2016    1  D01    8.0
1              4         1  2016    2  D01   12.0
2              4         1  2016    3  D01   11.0
3              4         1  2016    4  D01    8.0
4              4         1  2016    5  D01    7.0
...          ...       ...   ...  ...  ...    ...
225241        60        14  2019    8  D31   98.0
225242        60        14  2019    9  D31    0.0
225243        60        14  2019   10  D31   47.0
225244        60        14  2019   11  D31    0.0
225245        60        14  2019   12  D31    4.0

[225246 rows x 6 columns]

4.-Añadir una columna con la fecha a partir de la concatenación del año, el mes y el día

5.- Eliminar las filas con fechas no válidas y ordenar el DataFrame por estaciones contaminantes y fecha

In [ ]:
#Limpieza
dfEmReduced['DIA'] = dfEmReduced.DIA.str.strip('D')

#Concatenación de las columnas de ANO, MES y DIA
dfEmReduced['FECHA'] = dfEmReduced.ANO.apply(str) + '/' + dfEmReduced.MES.apply(str) + '/' + dfEmReduced.DIA.apply(str)

#Conversión a tipo de dato DATETIME
dfEmReduced['FECHA'] = pd.to_datetime(dfEmReduced.FECHA, format='%Y/%m/%d', infer_datetime_format=True, errors='coerce')

dfEmReduced

        ESTACION  MAGNITUD   ANO  MES DIA  VALOR      FECHA
0              4         1  2016    1  01    8.0 2016-01-01
1              4         1  2016    2  01   12.0 2016-02-01
2              4         1  2016    3  01   11.0 2016-03-01
3              4         1  2016    4  01    8.0 2016-04-01
4              4         1  2016    5  01    7.0 2016-05-01
...          ...       ...   ...  ...  ..    ...        ...
225241        60        14  2019    8  31   98.0 2019-08-31
225242        60        14  2019    9  31    0.0        NaT
225243        60        14  2019   10  31   47.0 2019-10-31
225244        60        14  2019   11  31    0.0        NaT
225245        60        14  2019   12  31    4.0 2019-12-31

[225246 rows x 7 columns]

In [ ]:
#Limpieza con isnat
dfEmReduced = dfEmReduced.drop(dfEmReduced[np.isnat(dfEmReduced.FECHA)].index)

#Ordenamiento del dataframe por estación, *contaminante y fecha
#Se asume que se refiere a al campo MAGNITUD, dado que es el único que expresaría el nivél de contaminación total, mas no su valor diario
dfEmReduced.sort_values(['ESTACION', 'MAGNITUD', 'FECHA'])

        ESTACION  MAGNITUD   ANO  MES DIA  VALOR      FECHA
0              4         1  2016    1  01    8.0 2016-01-01
7266           4         1  2016    1  02    7.0 2016-01-02
14532          4         1  2016    1  03    6.0 2016-01-03
21798          4         1  2016    1  04    6.0 2016-01-04
29064          4         1  2016    1  05    7.0 2016-01-05
...          ...       ...   ...  ...  ..    ...        ...
196181        60        14  2019   12  27   17.0 2019-12-27
203447        60        14  2019   12  28   13.0 2019-12-28
210713        60        14  2019   12  29   14.0 2019-12-29
217979        60        14  2019   12  30    5.0 2019-12-30
225245        60        14  2019   12  31    4.0 2019-12-31

[221158 rows x 7 columns]

6.- Mostrar las estaciones y los *contaminantes (MAGNITUD) disponibles en el DataFrame.

### Estaciones

In [ ]:
print(dfEmReduced.ESTACION.unique())

[ 4  8 11 16 17 18 24 27 35 36 38 39 40 47 48 49 50 54 55 56 57 58 59 60]

### Magnitudes

In [ ]:
print(dfEmReduced.MAGNITUD.unique())

[ 1  6  7  8 12  9 10 14 20 30 35 42 43 44]

7.- Crear una función que reciba una estación, un contaminante y un rango de fechas y devuelva una serie con las emisiones del contaminante dado en la estación y rango de fechas dado.

In [ ]:
#Busca emisiones de cierta magnitud y en cierta estación en un rango de fechas
def emissions(estacion, magnitud, init, fin):
    return dfEmReduced[(dfEmReduced.ESTACION == estacion) & (dfEmReduced.MAGNITUD == magnitud) & (dfEmReduced.FECHA >= init) & (dfEmReduced.FECHA <= fin)].sort_values('FECHA').VALOR


emissions(35, 8, dt.datetime.strptime('2018/10/25', '%Y/%m/%d'), dt.datetime.strptime('2019/02/12', '%Y/%m/%d'))

178803    60.0
186069    61.0
193335    42.0
200601    38.0
207867    40.0
          ...
57085     51.0
64351     41.0
71617     14.0
78883     38.0
86149     46.0
Name: VALOR, Length: 111, dtype: float64

8.- Mostrar un resumen descriptivo (mínimo, máximo, media, etc.) para cada contaminante.

In [ ]:
dfEmReduced.groupby('MAGNITUD').VALOR.describe()

            count       mean         std   min    25%    50%    75%       max
MAGNITUD
1         14610.0   7.428953    7.012504  0.00   4.00   7.00  10.00    610.00
6         14610.0   0.350233    0.215935  0.00   0.20   0.30   0.40     14.90
7         35064.0  20.446412  135.123509  0.00   4.00   9.00  23.00  24742.00
8         35064.0  37.677618   20.118050  0.00  22.00  35.00  50.00    148.00
9          8948.0  10.087729   10.643591  0.00   6.00   9.00  13.00    850.00
10        17897.0  18.772923   35.723619  0.00  10.00  16.00  24.00   4481.00
12        35064.0  67.959417   61.443940  0.00  29.00  48.00  84.00   1005.00
14        20454.0  49.941772   24.753120  0.00  31.00  52.00  69.00    336.00
20         8766.0   2.364944    4.236706  0.00   0.80   1.60   2.80    195.00
30         8766.0   0.531371    0.538180  0.00   0.20   0.40   0.70     15.10
35         8766.0   0.479751    1.183618  0.00   0.10   0.20   0.50     35.70
42         4383.0   1.400897    0.251836 -0.01   1.25   1.38   1.54      3.09
43         4383.0   1.292923    0.230898 -0.14   1.17   1.28   1.43      2.77
44         4383.0   0.108941    0.068776  0.00   0.06   0.10   0.14      1.31

9.- Mostrar un resumen descriptivo para cada contaminante por distritos.

In [ ]:
dfEmReduced.groupby(['ESTACION', 'MAGNITUD']).VALOR.describe()

                    count       mean        std  min   25%   50%    75%    max
ESTACION MAGNITUD
4        1         1461.0   7.329911  16.379050  1.0   4.0   7.0    9.0  610.0
         6         1461.0   0.411499   0.172902  0.1   0.3   0.4    0.5    1.3
         7         1461.0  31.939767  37.667968  0.0   8.0  16.0   42.0  239.0
         8         1461.0  44.398357  17.766063  0.0  31.0  43.0   55.0  105.0
         12        1461.0  93.341547  72.436531  0.0  44.0  69.0  119.0  467.0
...                   ...        ...        ...  ...   ...   ...    ...    ...
60       7         1461.0  12.326489  19.593109  1.0   2.0   4.0   12.0  151.0
         8         1461.0  31.125941  18.101896  3.0  18.0  27.0   41.0  101.0
         10        1461.0  17.033539  12.205022  1.0   9.0  14.0   21.0  215.0
         12        1461.0  50.023956  45.933843  6.0  22.0  33.0   60.0  328.0
         14        1461.0  60.718001  26.309952  4.0  42.0  65.0   81.0  119.0

[153 rows x 8 columns]

10.- Crear una función que reciba una estación y un contaminante y devuelva un resumen descriptivo de las emisiones del contaminante indicado en la estación indicada.

In [ ]:
#Dado una magnitud y estación, devuelve un resumen de la emisión y contaminación
def contamSummary(estacion, magnitud):
    return dfEmReduced[(dfEmReduced.ESTACION == estacion) & (dfEmReduced.MAGNITUD == magnitud)].VALOR.describe()

print('Resumen #1:\n', contamSummary(35, 7),'\n', sep='')
print('Resumen #2:\n', contamSummary(54, 8),'\n', sep='')
print('Resumen #3:\n', contamSummary(58, 12), sep='')

Resumen #1:
count    1461.000000
mean       21.342231
std        25.849603
min         0.000000
25%         6.000000
50%        11.000000
75%        24.000000
max       172.000000
Name: VALOR, dtype: float64

Resumen #2:
count    1461.000000
mean       37.500342
std        19.053696
min         4.000000
25%        23.000000
50%        33.000000
75%        49.000000
max       116.000000
Name: VALOR, dtype: float64

Resumen #3:
count    1461.000000
mean       24.676249
std        18.975107
min         0.000000
25%        12.000000
50%        20.000000
75%        30.000000
max       158.000000
Name: VALOR, dtype: float64

11.- Crear una función que devuelva las emisiones medias mensuales de un contaminante y un año dados para todos las estaciones.

In [ ]:
def contamSummaryMonthly(magnitud, ano):
    return dfEmReduced[(dfEmReduced.MAGNITUD == magnitud) & (dfEmReduced.ANO == ano)].groupby(['ESTACION', 'MES']).VALOR.mean().unstack('MES')

print('Resumen #1:\n', contamSummaryMonthly(9, 2019),'\n', sep='')
print('Resumen #2:\n', contamSummaryMonthly(5, 2016),'\n', sep='')
print('Resumen #3:\n', contamSummaryMonthly(8, 2017), sep='')

Resumen #1:
MES              1          2          3         4         5          6   \
ESTACION
8         13.806452  13.214286  15.193548  7.566667  6.548387   9.033333
24        12.870968  12.071429   7.548387  5.433333  6.225806  12.500000
38        14.354839  14.250000   8.548387  6.866667  6.322581   8.700000
47        13.741935  13.535714   7.838710  4.966667  5.290323   7.800000
48        12.129032  12.821429   8.000000  6.366667  5.870968   9.366667
50        14.129032  13.535714   8.193548  7.166667  5.774194   8.400000
56        18.548387  16.714286  10.225806  7.900000  7.258065   9.333333

MES              7          8          9          10        11         12
ESTACION
8         11.741935   9.290323   8.066667  10.225806  5.866667  10.290323
24        11.903226   8.387097   7.266667   8.516129  4.366667   9.225806
38         8.032258   7.322581   8.966667  10.354839  5.566667  11.677419
47        11.258065  11.612903  16.266667   9.387097  5.033333   9.967742
48        14.258065   8.612903   8.033333  10.000000  6.066667  11.870968
50        10.741935   7.064516   5.933333   9.032258  6.233333  11.193548
56        12.483871  13.161290  12.733333  12.516129  8.366667  12.709677

Resumen #2:
Empty DataFrame
Columns: []
Index: []

Resumen #3:
MES              1          2          3          4          5          6   \
ESTACION
4         57.225806  50.892857  45.451613  41.966667  40.483871  44.300000
8         69.387097  59.785714  61.645161  51.566667  54.290323  58.066667
11        55.290323  43.678571  43.354839  33.466667  34.903226  39.300000
16        52.548387  45.000000  43.322581  28.766667  29.064516  32.566667
17        66.935484  49.357143  48.129032  31.300000  31.935484  24.700000
18        56.161290  44.392857  41.000000  31.833333  30.387097  29.266667
24        33.838710  25.750000  22.161290  16.900000  15.064516  12.366667
27        51.096774  40.392857  40.741935  28.533333  28.774194  28.166667
35        60.161290  49.607143  46.645161  42.100000  41.451613  43.933333
36        54.225806  44.142857  43.032258  30.166667  31.516129  31.900000
38        59.903226  45.892857  43.580645  34.266667  33.548387  35.700000
39        55.580645  42.464286  42.387097  31.100000  30.290323  32.266667
40        57.032258  44.821429  44.483871  31.833333  32.064516  31.600000
47        59.903226  46.178571  42.580645  33.200000  30.548387  29.033333
48        49.290323  41.428571  41.774194  27.666667  28.838710  31.866667
49        45.967742  35.035714  31.451613  22.100000  19.838710  20.233333
50        55.193548  44.035714  41.516129  29.900000  34.032258  36.566667
54        49.000000  36.142857  37.258065  25.900000  26.258065  29.066667
55        57.064516  50.035714  50.096774  36.933333  35.903226  33.966667
56        69.387097  54.107143  49.580645  44.866667  43.483871  43.333333
57        50.290323  36.964286  35.741935  23.433333  23.064516  23.766667
58        27.870968  17.250000  15.096774  11.333333  11.774194  13.933333
59        28.322581  32.071429  33.967742  20.166667  20.290323  18.600000
60        55.225806  39.321429  36.645161  25.466667  23.258065  23.933333

MES              7          8          9          10         11         12
ESTACION
4         41.903226  35.903226  52.066667  63.677419  66.166667  53.516129
8         56.516129  45.129032  62.066667  72.225806  79.700000  71.483871
11        36.000000  28.548387  44.066667  60.225806  69.900000  59.580645
16        33.741935  28.419355  40.900000  50.419355  60.900000  55.387097
17        38.935484  35.032258  50.533333  63.322581  79.700000  61.709677
18        31.548387  27.419355  40.400000  54.741935  63.000000  53.419355
24        15.612903  14.548387  22.100000  37.516129  46.133333  35.193548
27        31.580645  28.548387  38.800000  51.870968  58.866667  53.290323
35        43.967742  39.677419  42.266667  65.806452  62.333333  51.000000
36        33.258065  33.451613  46.033333  51.741935  62.500000  56.451613
38        33.967742  26.322581  43.633333  59.677419  73.400000  60.032258
39        32.709677  22.709677  41.166667  59.290323  67.666667  59.580645
40        33.290323  28.129032  41.533333  49.580645  61.333333  53.387097
47        31.064516  27.000000  42.700000  56.935484  66.600000  55.225806
48        29.870968  24.451613  36.433333  49.935484  61.966667  54.774194
49        21.096774  17.193548  30.533333  41.193548  53.500000  44.870968
50        36.612903  27.774194  24.733333  48.612903  59.200000  54.032258
54        32.032258  27.806452  42.300000  53.129032  67.500000  50.677419
55        37.709677  33.387097  46.066667  57.935484  64.766667  59.516129
56        52.774194  48.096774  62.100000  81.161290  86.833333  73.548387
57        24.709677  20.709677  31.033333  42.580645  57.066667  48.806452
58        14.548387  11.967742  16.833333  23.193548  30.000000  24.580645
59        21.225806  17.741935  29.133333  35.774194  44.966667  41.677419
60        24.290323  20.064516  32.400000  42.612903  55.033333  47.903226

12.- Crear un función que reciba una estación de medición y devuelva un DataFrame con las medias mensuales de los distintos tipos de contaminantes.

In [ ]:
def contamTypeSummaryMonthly(estacion, ano):
  data = dfEmReduced[(dfEmReduced.ESTACION == estacion) & (dfEmReduced.ANO == ano)].groupby(['MES']).VALOR.mean()
  df = pd.DataFrame(data)
  return df


contamTypeSummaryMonthly(18, 2019)

         VALOR
MES
1    29.447419
2    27.604643
3    18.911613
4    16.100000
5    15.654839
6    16.600000
7    17.738710
8    14.796774
9    14.599333
10   18.894194
11   13.286667
12   20.441613